export Navigator from './Navigator/Navigator'
export DetailsContainer from './Details/DetailsContainer'
export SplashContainer from './Splash/SplashContainer'
export AppContainer from './App/AppContainer'
export FooterTabsContainer from './FooterTabs/FooterTabsContainer'
